### ISSUE TITLE
Protobuf incompatibility

### ISSUE THREAD

**Issue by petersohn** [jjmontesl/python-clementine-remote#5]
I have python-clementine-remote 1.0.3 installed from pip. When trying to run the client, I get the following error message:

```
Traceback (most recent call last):
  File "/home/petersohn/.local/bin/clementine-remote", line 5, in <module>
    from clementineremote.cli import main
  File "/home/petersohn/.local/lib/python3.9/site-packages/clementineremote/__init__.py", line 17, in <module>
    from .clementine import ClementineRemote
  File "/home/petersohn/.local/lib/python3.9/site-packages/clementineremote/clementine.py", line 21, in <module>
    import clementineremote.remotecontrolmessages_pb2 as cr
  File "/home/petersohn/.local/lib/python3.9/site-packages/clementineremote/remotecontrolmessages_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/petersohn/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

I have protobuf 4.21.2 installed from pip.

**Comment by NathanSalapat** [comment]
I am having the same issue, trying to connect to my Clementine players via homeassistant.

**Comment by fantafe** [comment]
I am also having the same issue to connect to Clementine player via homeassistant. I get the following error when trying to integrate through configuration.yaml.

"Platform error media_player.clementine - Exception importing homeassistant.components.clementine.media_player
"

**Comment by martin3000** [comment]
I created PR #7 
(pull request)
